# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: CV
    url: cv/
    weight: 2
  - name: News
    url: news/
    weight: 3
  - name: Research
    url: research/
    weight: 4
  - name: Publications
    url: publication/
    weight: 5
  - name: Resources
    url: resources/
    weight: 7

